name: mac
authors:
  - Kenneth Endfinger <kaendfinger@gmail.com>
  - Logan Gorence <loganjohngorence@gmail.com>
description: macOS utility package
version: 2.0.0
homepage: https://github.com/DirectMyFile/macOS.dart
dependencies:
  xml: ">=2.0.0 <3.0.0"
  crypto: ">=0.9.0 <1.0.0"
  jsonx: ">=2.0.0 <3.0.0"
