name: mac
authors:
  - Kenneth Endfinger <kaendfinger@gmail.com>
  - Logan Gorence <logan@gorence.xyz>
description: Library that provides access to many of the amazing macOS scripting and automation APIs.
version: 3.0.0
homepage: https://github.com/SpinlockLabs/mac.dart
dependencies:
  petitparser: ^2.2.1
  xml: ^3.4.1
  pedantic: ^1.5.0
dev_dependencies:
  test: ^1.5.3
