name: osx
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Tools for OSX
version: 1.1.0
homepage: https://github.com/DirectMyFile/osx.dart
dependencies:
  xml: ">=2.0.0 <3.0.0"
  crypto: ">=0.9.0 <1.0.0"
  jsonx: ">=2.0.0 <3.0.0"
